
    type ApprovedUser @model @auth(rules: [{ allow: private }]) {
      id: ID!
      email: String! @index(name: "byEmail")
      givenName: String!
      familyName: String!
      phoneNumber: String
      isActive: Boolean!
      approvedBy: String
      approvedDate: AWSDateTime
      createdDate: AWSDateTime!
    }

    type CognitoUser {
      username: String!
      email: String!
      givenName: String
      familyName: String
      phoneNumber: String
      userStatus: String!
      userCreateDate: AWSDateTime
      enabled: Boolean!
    }

    type Query {
      listCognitoUsers: [CognitoUser] @function(name: "cognitoAdmin") @auth(rules: [{ allow: private }])
    }
  